
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gocd-agent
  namespace: prod-gocd-server
  labels: 
    app: gocd-agent
spec:
  selector:
    matchLabels:
      app: gocd-agent
      tier: agent
  replicas: 1
  template:
    metadata:
      labels:
        app: gocd-agent
        tier: agent
    spec:
      containers:
      - name: gocd-agent
        image: manukoli1986/gocd-agent:v1
#        image: gocd/gocd-agent-ubuntu-16.04:v18.12.0
        env: 
        - name: GO_SERVER_URL
          value: "https://gocd-master-internal:8154/go/"

        volumeMounts:
        - name: gocd-agent-godata
          mountPath: /godata
      volumes:
      - name: gocd-agent-godata
        persistentVolumeClaim:
          claimName: gocd-agent-pvc

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: gocd-agent-pvc
  namespace: prod-gocd-server
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
