
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gocd-agent-deployment
  namespace: prod-gocd-server
  labels: 
    app: gocd-agent
spec:
  selector:
    matchLabels:
      app: gocd-agent
      tier: agent
  replicas: 3
  template:
    metadata:
      labels:
        app: gocd-agent
        tier: agent
    spec:
      containers:
      - name: gocd-agent
        image: gocd/gocd-agent-ubuntu-16.04:v18.12.0
        env: 
        - name: GO_SERVER_URL
          value: "https://gocd-master-internal:8154/go/"
#        env:
#          GO_SERVER_URL=https://gocd-server:port/go
#          GO_AGENT_SYSTEM_PROPERTIES=-Dgo.agent.status.api.bind.port=8158
#        ports:
#        - containerPort: 8158
#      volumes:
#      - name: test-volume
#        vsphereVolume:
#      	  volumePath: "[DatastoreName] volumes/myDisk"
#          fsType: ext4
