kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: gocd-server-pvc
  namespace: gocd-server
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: gocd-agent-pvc
  namespace: gocd-server
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
