apiVersion: v1
kind: PersistentVolume
metadata:
  name: gocd-server-pv
  namespace: prod-gocd-server
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  vsphereVolume:
#    volumePath: "[datastore1] volumes/myDisk"
    volumePath: "[MITUCSBPaaS01_VSP56418_003] kubevols/gocd-server-pv"
    fsType: ext4

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: gocd-agent-pv
  namespace: prod-gocd-server
spec:
  capacity:
    storage: 500Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  vsphereVolume:
    volumePath: "[MITUCSBPaaS01_VSP56418_003] kubevols/gocd-agent-pv"
    fsType: ext4

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: gocd-server-pvc
  namespace: prod-gocd-server
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Gi

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: gocd-agent-pvc
  namespace: prod-gocd-server
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: gocd-agent-pvc1
  namespace: prod-gocd-server
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: gocd-agent-pvc2
  namespace: prod-gocd-server
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: gocd-agent-pvc3
  namespace: prod-gocd-server
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: gocd-agent-pvc4
  namespace: prod-gocd-server
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
