kind: PersistentVolume
apiVersion: v1
metadata:
  name: gocd-server-pv
  labels:
    type: vsphere
spec:
  capacity:
    storage: 1000Gi
  accessModes:
    - ReadWriteMany
  awsElasticBlockStore:
    volumeID: <your-volume-id>
    fsType: ext4
